Fix:
CMake Error at /usr/src/myapp/fluent-bit/build/Rust/src/out_rust_stdout-stamp/out_rust_stdout-build-Debug.cmake:16 (message):
  Command failed: 101

   '/usr/bin/cmake' '-E' 'env' 'CARGO_TARGET_DIR=/usr/src/myapp/fluent-bit/build/library' 'BINDGEN_HEADER_DIRS=-I/usr/src/myapp/fluent-bit/include -I/usr/src/myapp/fluent-bit/lib -I/usr/src/myapp/fluent-bit/lib/flb_libco -I/usr/src/myapp/fluent-bit/lib/rbtree -I/usr/src/myapp/fluent-bit/lib/msgpack-3.2.0/include -I/usr/src/myapp/fluent-bit/lib/chunkio/include -I/usr/src/myapp/fluent-bit/lib/LuaJIT-2.1.0-beta3/src -I/usr/src/myapp/fluent-bit/lib/monkey/include -I/usr/src/myapp/fluent-bit/lib/mbedtls-2.16.3/include -I/usr/src/myapp/fluent-bit/lib/sqlite-amalgamation-3310000 -I/usr/src/myapp/fluent-bit/lib/mpack-amalgamation-1.0/src -I/usr/src/myapp/fluent-bit/lib/miniz -I/usr/src/myapp/fluent-bit/lib/onigmo -I/usr/src/myapp/fluent-bit/build/include -I/usr/src/myapp/fluent-bit/lib/tutf8e/include -I/usr/src/myapp/fluent-bit/build/include -I/usr/src/myapp/fluent-bit/build/backtrace-prefix/include -I/usr/src/myapp/fluent-bit/build/include' 'CMAKE_ARCHIVE_OUTPUT_DIRECTORY=/usr/src/myapp/fluent-bit/build/library' 'CMAKE_LIBRARY_OUTPUT_DIRECTORY=/usr/src/myapp/fluent-bit/build/lib' 'cargo' 'build' '-vv'

  See also

    /usr/src/myapp/fluent-bit/build/Rust/src/out_rust_stdout-stamp/out_rust_stdout-build-*.log

make[2]: *** [plugins/out_rust_stdout/CMakeFiles/out_rust_stdout.dir/build.make:112: Rust/src/out_rust_stdout-stamp/out_rust_stdout-build] Error 1
make[1]: *** [CMakeFiles/Makefile2:2715: plugins/out_rust_stdout/CMakeFiles/out_rust_stdout.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
Removing intermediate container 6de69f654a2d
 ---> d4f2b593b0d4
Step 8/8 : RUN ls /usr/src/myapp/fluent-bit/build/Rust/src/out_rust_stdout-stamp/ && cat /usr/src/myapp/fluent-bit/build/Rust/src/out_rust_stdout-stamp/out_rust_stdout-build-*.log # && echo $PWD && tree && install bin/fluent-bit /fluent-bit/bin/ && make clean
 ---> Running in 454d6a9c08fe
out_rust_stdout-build-Debug.cmake
out_rust_stdout-build-err.log
out_rust_stdout-build-out.log
out_rust_stdout-configure
out_rust_stdout-download
out_rust_stdout-mkdir
out_rust_stdout-patch
out_rust_stdout-update
    Updating crates.io index
error: no matching package named `fluent_bit_binding` found
location searched: /usr/src/myapp/fluent-bit/plugins/rust_binding
required by package `out_rust_stdout v0.1.0 (/usr/src/myapp/fluent-bit/plugins/out_rust_stdout)`